### ISSUE TITLE
Overrides Sass comments

### ISSUE THREAD

**Issue by ezekg** [emmetio/emmet-atom#101]
When using `cmd+/` it produces CSS `/* comments */`. Sass uses `// comments`. When attempting to comment out code blocks, Emmet looks like it tries to do Sass comments by adding almost seemingly random backward slashes like below. This is the result after selecting the block and toggling the comments about 3-4 times.

``` scss
/* path {
    stroke: \\\\\$color__orange--lightest;
    stroke-dasharray: 1000;
    stroke-dashoffset: 1000;
    @include animation(draw 5s ease-in-out forwards);
} */
```

Currently have to disable Emmet when working within my Sass files. At least add the ability to disable certain Emmet shortcuts so that this doesn't happen.
##
